### ISSUE TITLE
Chevauchement images dans Drag and drop

### ISSUE THREAD

**Issue by sarahlachise** [pfautrero/xia#16]
Serait-il possible que Xia accepte le chevauchement d'images dans le mini jeu "slip&deposit" ? 
Actuellement, si on glisse plusieurs images dans une même zone de dépôt et si ces images se superposent en leur centre, le score n'est pas pris en compte. 
Merci :-)

**Comment by pfautrero** [comment]
@cdbc245ee25c070dad94b9142cdbaa2ac8032362
